Repository ansible-middleware/amq, pull requests merged in 2024-03, with the labels that each got.

#115 rework molecule's prepare to works with sudo user on targets
  molecule/amq_upgrade/verify.yml
  molecule/default/verify.yml
  molecule/mask_passwords/verify.yml
  molecule/prepare.yml
  molecule/static_cluster/prepare.yml
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/tasks/install.yml
Labels: minor_changes

#116 Parameter `activemq_logger_config_template` allows relative paths
  .ansible-lint
  molecule/amq_upgrade/converge.yml
  molecule/amq_upgrade/prepare.yml
  molecule/mask_passwords/converge.yml
  molecule/mask_passwords/templates/logging/custom.log4j2.properties.j2
  molecule/static_cluster/converge.yml
  molecule/static_cluster/prepare.yml
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/tasks/acceptors.yml
  roles/activemq/tasks/address_settings.yml
  roles/activemq/tasks/addresses.yml
  roles/activemq/tasks/broker_connections.yml
  roles/activemq/tasks/configure_broker.yml
  roles/activemq/tasks/connectors.yml
  roles/activemq/tasks/diverts.yml
  roles/activemq/tasks/firewalld.yml
  roles/activemq/tasks/install.yml
  roles/activemq/tasks/journal.yml
  roles/activemq/tasks/keystores.yml
  roles/activemq/tasks/main.yml
  roles/activemq/tasks/prereqs.yml
  roles/activemq/tasks/restart.yml
  roles/activemq/tasks/start.yml
  roles/activemq/tasks/systemd.yml
  roles/activemq/tasks/upgrade.yml
  roles/activemq/tasks/user_roles.yml
  roles/activemq/tasks/validate_config.yml
  roles/activemq/templates/amq_broker.sysconfig.j2
Labels: major_changes

#117 `activemq_config_override_template` allows to use custom broker.xml templates
  .github/workflows/ci.yml
  molecule/custom_xml/converge.yml
  molecule/custom_xml/molecule.yml
  molecule/custom_xml/prepare.yml
  molecule/custom_xml/roles
  molecule/custom_xml/templates/broker.xml.j2
  molecule/custom_xml/verify.yml
  molecule/prepare.yml
  roles/activemq/files/artemis-server.xsd
  roles/activemq/tasks/main.yml
  roles/activemq/tasks/prereqs.yml
  roles/activemq/tasks/systemd.yml
  roles/activemq/vars/main.yml
Labels: bugfixes

#118 Update activemq default to 2.32 / amq_broker to 7.11.6
  molecule/amq_upgrade/verify.yml
  molecule/custom_xml/verify.yml
  molecule/default/molecule.yml
  molecule/default/verify.yml
  molecule/mask_passwords/verify.yml
  molecule/static_cluster/verify.yml
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/files/artemis-configuration-2.32.xsd
  roles/activemq/meta/argument_specs.yml
  roles/activemq/meta/main.yml
Labels: minor_changes
