Repository ansible-middleware/amq, pull requests merged in 2024-09, with the labels that each got.

#161 Add more journal configs
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/vars/main.yml
Labels: minor_changes

#163 Fix condition for transferring key/trust store
  roles/activemq/README.md
  roles/activemq/tasks/keystores.yml
  roles/activemq/templates/amq_broker.sysconfig.j2
Labels: bugfixes

#164 New `activemq_console_bind_url` parameter
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/tasks/configure_files.yml
Labels: minor_changes

#165 Add `activemq_systemd_expand_environment` parameter
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/templates/amq_broker.service.j2
Labels: minor_changes

#166 Fix scenarios where duplicate XInclude can be present
  roles/activemq/tasks/address_settings.yml
  roles/activemq/tasks/addresses.yml
  roles/activemq/tasks/diverts.yml
Labels: bugfixes

#167 Add `web_origin` parameter to `activemq_facts` module
  plugins/modules/activemq_facts.py
Labels: minor_changes

#168 Allow to explicitly list `cluster-connections`
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/tasks/connectors.yml
  roles/activemq/tasks/main.yml
  roles/activemq/templates/cluster_connections.broker.xml.j2
  roles/activemq/templates/ha_policy.xml.j2
Labels: minor_changes

#171 Parameters for `activemq_addresses` as a dictionary
  molecule/default/converge.yml
  molecule/replication/converge.yml
  roles/activemq/templates/addresses.broker.xml.j2
  roles/activemq/templates/modular/addresses.xml.j2
Labels: minor_changes

#173 ensure targets use supported OS family
  roles/activemq/tasks/prereqs.yml
Labels: enhancement

#174 Check broadcast/discovery groups absent with `provided` discovery
  roles/activemq/tasks/configure_artemis.yml
  roles/activemq/tasks/connectors.yml
  roles/activemq/tasks/jgroups.yml
Labels: bugfixes

#175 New parameter to configure clustering without HA
  .github/workflows/ci.yml
  molecule/live_only/converge.yml
  molecule/live_only/molecule.yml
  molecule/live_only/prepare.yml
  molecule/live_only/roles
  molecule/live_only/verify.yml
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
  roles/activemq/tasks/configure_artemis.yml
  roles/activemq/tasks/configure_broker.yml
  roles/activemq/tasks/connectors.yml
  roles/activemq/tasks/main.yml
  roles/activemq/templates/connectors.broker.xml.j2
  roles/activemq/templates/ha_policy.xml.j2
Labels: bugfixes

#178 Fix broker.xml connector and connector-ref when using federation
  .github/workflows/ci.yml
  molecule/federation/converge.yml
  molecule/federation/molecule.yml
  molecule/federation/prepare.yml
  molecule/federation/roles
  molecule/federation/verify.yml
  roles/activemq/defaults/main.yml
  roles/activemq/tasks/connectors.yml
  roles/activemq/tasks/federations.yml
  roles/activemq/templates/federations.broker.xml.j2
Labels: bugfixes

#179 Fix invalid `broker-connections` when boolean options are used
  .github/workflows/ci.yml
  molecule/mirroring/converge.yml
  molecule/mirroring/molecule.yml
  molecule/mirroring/prepare.yml
  molecule/mirroring/roles
  molecule/mirroring/verify.yml
  roles/activemq/templates/broker_connections.broker.xml.j2
Labels: bugfixes

#186 Update default for `activemq_systemd_wait_for_log_ha_string`
  roles/activemq/README.md
  roles/activemq/defaults/main.yml
  roles/activemq/meta/argument_specs.yml
Labels: bugfixes
